-- MySQL Script generated by MySQL Workbench
-- Mon Feb  7 11:53:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ctenar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ctenar` (
  `cislo_karty` INT NOT NULL,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(50) NOT NULL,
  `datum_narozeni` DATE NOT NULL,
  `telefon` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `ulice` VARCHAR(60) NOT NULL,
  `CP` VARCHAR(45) NOT NULL,
  `PSC` INT(5) NOT NULL,
  `mesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cislo_karty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `idautor` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kniha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kniha` (
  `idkniha` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `pocet_stran` INT NOT NULL,
  `popis` TEXT NOT NULL,
  `datum_pujceni` DATE NULL,
  `termin_dodani` DATE NULL,
  `stav` ENUM('pujceno', 'vraceno') NOT NULL,
  `ctenar_cislo_karty` INT NOT NULL,
  PRIMARY KEY (`idkniha`),
  INDEX `fk_kniha_ctenar_idx` (`ctenar_cislo_karty` ASC),
  CONSTRAINT `fk_kniha_ctenar`
    FOREIGN KEY (`ctenar_cislo_karty`)
    REFERENCES `mydb`.`ctenar` (`cislo_karty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kniha_has_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kniha_has_autor` (
  `kniha_idkniha` INT NOT NULL,
  `autor_idautor` INT NOT NULL,
  PRIMARY KEY (`kniha_idkniha`, `autor_idautor`),
  INDEX `fk_kniha_has_autor_autor1_idx` (`autor_idautor` ASC),
  INDEX `fk_kniha_has_autor_kniha1_idx` (`kniha_idkniha` ASC),
  CONSTRAINT `fk_kniha_has_autor_kniha1`
    FOREIGN KEY (`kniha_idkniha`)
    REFERENCES `mydb`.`kniha` (`idkniha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kniha_has_autor_autor1`
    FOREIGN KEY (`autor_idautor`)
    REFERENCES `mydb`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
